### ISSUE TITLE
Montagem

### ISSUE THREAD

**Issue by printRafaelprog** [SkyRats/skyrats_cbr_2022#7]
Documentação das versões e problemas com a montagem do drone 2022

**Comment by printRafaelprog** [comment]
# Lista de componentes

- Controladora de voo 
- Telemetria
- RC
- SBC P3450 Jetson nano
- 1 PMB
- 1 UBEC
- 1 Esc
- Eletroímã
- Realsense
- Lidar (talvez)
- 4 Leds -> 12V, RGB
- 3 Buzzer -> 5V

## Plaquinha

- 4 Leds
- 3 Buzzer
- 1 Eletroimã

**Comment by Beserrovsky** [comment]
# Jetson Nano Developer Kit

- Modelo: P3450
- Entrada: 5V max 4A
- OS: [Write image to SD card - Nvidia Jetson Nano](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write)
- User Guide: [JETSON NANO DEVELOPER KIT](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#)

## Tasks:

- [ ] Fazer ligar
- [ ] Instalar OS
- [ ] Configurar PX4 VIO

**Comment by Beserrovsky** [comment]
# PX4 VIO -> Nvidia's Jetson Nano & Intel's Realsense T265

- Original repos: [Auterion](https://github.com/Auterion) / [VIO](https://github.com/Auterion/VIO)
- Youtube video: [PX4 VIO Setup with Jetson Nano and Intel T265 - Auterion VIO Fork](https://www.youtube.com/watch?v=Brkk0ZmnGgs)
- Video fork: [dbaldwin](https://github.com/dbaldwin) / [VIO](https://github.com/dbaldwin/VIO)
- Video Gist: [PX4 VIO w/ Jetson Nano, Intel T2654, and Pixhawk (NXP Version)](https://gist.github.com/dbaldwin/041735a774bf46a82ee98bbbe28a7939)
- [Real Sense Install in Jetson Nano](https://www.youtube.com/watch?v=lL3zxwN5Lnw)

**Comment by printRafaelprog** [comment]
# LISTA DE COMPRAS

- Bateria de Controle 
- Bateria de drone 
- Fonte para Odroid (5V 4A)

**Comment by Beserrovsky** [comment]
# Odroid XU4

- Modelo: Xu4
- Entrada: 5V 4A
- OS: [Ubuntu Minimal 20.04](https://wiki.odroid.com/odroid-xu4/os_images/linux/ubuntu_5.4/minimal/20200812)
- Wiki: [HardKernel's odroid xu4](https://wiki.odroid.com/odroid-xu4/odroid-xu4)

## Tasks

- [x] Instalar OS
- [ ] Script com configuração
- [ ] Configurar PX4 VIO

**Comment by Beserrovsky** [comment]
# Raspberry Pi 3B

- Modelo: 3B
- Entrada: 5V 3A
- OS: [Ubuntu Server 20.04 LTS 64bit] -> rpi-imager

## Links
- [Tutorial realsense rpi 3B ubuntu 16.04 Parte 1](https://discuss.ardupilot.org/t/integration-of-ardupilot-and-vio-tracking-camera-part-1-getting-started-with-the-intel-realsense-t265-on-rasberry-pi-3b/43162)
- [Tutorial realsense rpi 3B ubuntu 16.04 Parte 2](https://discuss.ardupilot.org/t/integration-of-ardupilot-and-vio-tracking-camera-part-2-complete-installation-and-indoor-non-gps-flights/43405)
- [Ardupilot wiki realsense rpi 4 e 3](https://ardupilot.org/rover/docs/common-vio-tracking-camera.html)
- [Ardupilot wiki realsense ubuntu 16.04 rpi 4 e 3](https://ardupilot.org/dev/docs/ros-vio-tracking-camera.html#ros-vio-tracking-camera)
- [Intel forum build realsense ubuntu 20.04 rpi 4](https://support.intelrealsense.com/hc/en-us/community/posts/1500000077181-Realsense-Install-Ubuntu-20-04-Raspberry-PI-4)

## Tasks

- [x] Instalar OS
- [ ] Script com configuração
- [ ] Build realsense
- [ ] Configurar Ardupilot VIO
- [ ] Adicionar GUI (?)

**Comment by Beserrovsky** [comment]
# Ubuntu Server 20.04.5 LTS on RPi 3B Config

## Default Steps

- Default user "ubuntu" pass "ubuntu"
- Change ubuntu pass to "skyrats123" temporarily
- Change Keyboard Layout -> `sudo dpkg-reconfigure keyboard-configuration`
- [Connect wifi](https://linuxconfig.org/ubuntu-20-04-connect-to-wifi-from-command-line)
- Enable SSH -> `sudo systemctl enable ssh`
- [Change Timezone](https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-20-04)
- Create new user
- Add to sudoers
- Run `sudo apt update && sudo apt upgrade -y`
- Run skyrats-workplace scripts
    - Mavros ...

**Comment by printRafaelprog** [comment]
# Coisas que estão faltando no citi que vamos pedir pro pessoal trazer

- medidor de bateria
- fonte para carregar as baterias
- Raspberry pi 
- Cartão sd
- fonte da Odroid
- Pixhawk 4
